/* tslint:disable */
/* eslint-disable */
/**
 * Image Auto Editor API
 * 이미지 자동 편집을 위한 REST API 서비스
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HTTPValidationError } from '../models';
/**
 * ProcImageApi - axios parameter creator
 * @export
 */
export const ProcImageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * image proc
         * @summary Proc Image
         * @param {any} tags 
         * @param {any} targetFilterTags 
         * @param {any} targetFilterNames 
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        procImageApiProcImagesRemovePostForm: async (tags: any, targetFilterTags: any, targetFilterNames: any, file: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tags' is not null or undefined
            if (tags === null || tags === undefined) {
                throw new RequiredError('tags','Required parameter tags was null or undefined when calling procImageApiProcImagesRemovePostForm.');
            }
            // verify required parameter 'targetFilterTags' is not null or undefined
            if (targetFilterTags === null || targetFilterTags === undefined) {
                throw new RequiredError('targetFilterTags','Required parameter targetFilterTags was null or undefined when calling procImageApiProcImagesRemovePostForm.');
            }
            // verify required parameter 'targetFilterNames' is not null or undefined
            if (targetFilterNames === null || targetFilterNames === undefined) {
                throw new RequiredError('targetFilterNames','Required parameter targetFilterNames was null or undefined when calling procImageApiProcImagesRemovePostForm.');
            }
            // verify required parameter 'file' is not null or undefined
            if (file === null || file === undefined) {
                throw new RequiredError('file','Required parameter file was null or undefined when calling procImageApiProcImagesRemovePostForm.');
            }
            const localVarPath = `/api/proc-images/remove`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();


            if (tags !== undefined) { 
                localVarFormParams.append('tags', tags as any);
            }

            if (targetFilterTags !== undefined) { 
                localVarFormParams.append('target_filter_tags', targetFilterTags as any);
            }

            if (targetFilterNames !== undefined) { 
                localVarFormParams.append('target_filter_names', targetFilterNames as any);
            }

            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProcImageApi - functional programming interface
 * @export
 */
export const ProcImageApiFp = function(configuration?: Configuration) {
    return {
        /**
         * image proc
         * @summary Proc Image
         * @param {any} tags 
         * @param {any} targetFilterTags 
         * @param {any} targetFilterNames 
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async procImageApiProcImagesRemovePostForm(tags: any, targetFilterTags: any, targetFilterNames: any, file: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await ProcImageApiAxiosParamCreator(configuration).procImageApiProcImagesRemovePostForm(tags, targetFilterTags, targetFilterNames, file, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProcImageApi - factory interface
 * @export
 */
export const ProcImageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * image proc
         * @summary Proc Image
         * @param {any} tags 
         * @param {any} targetFilterTags 
         * @param {any} targetFilterNames 
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async procImageApiProcImagesRemovePostForm(tags: any, targetFilterTags: any, targetFilterNames: any, file: any, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return ProcImageApiFp(configuration).procImageApiProcImagesRemovePostForm(tags, targetFilterTags, targetFilterNames, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProcImageApi - object-oriented interface
 * @export
 * @class ProcImageApi
 * @extends {BaseAPI}
 */
export class ProcImageApi extends BaseAPI {
    /**
     * image proc
     * @summary Proc Image
     * @param {any} tags 
     * @param {any} targetFilterTags 
     * @param {any} targetFilterNames 
     * @param {any} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcImageApi
     */
    public async procImageApiProcImagesRemovePostForm(tags: any, targetFilterTags: any, targetFilterNames: any, file: any, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return ProcImageApiFp(this.configuration).procImageApiProcImagesRemovePostForm(tags, targetFilterTags, targetFilterNames, file, options).then((request) => request(this.axios, this.basePath));
    }
}
