/* tslint:disable */
/* eslint-disable */
/**
 * Image Auto Editor API
 * 이미지 자동 편집을 위한 REST API 서비스
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DefaultApi } from './apis/default-api';
import { ProcImageApi } from './apis/proc-image-api';
import { TargetImagesApi } from './apis/target-images-api';
import { Configuration } from './configuration';
import customAxios from './customAxios';

const bkPath = window.APP_CONFIG.REST_API_URL;
const config = new Configuration({ basePath: bkPath });

const defaultApi = new DefaultApi(config, bkPath, customAxios);
const procImageApi = new ProcImageApi(config, bkPath, customAxios);
const targetImagesApi = new TargetImagesApi(config, bkPath, customAxios);

export { defaultApi, procImageApi, targetImagesApi };