/* tslint:disable */
/* eslint-disable */
/**
 * Image Auto Editor API
 * 이미지 자동 편집을 위한 REST API 서비스
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DefaultApi, ImageApi, ProcImageApi, TargetImagesApi } from './api';
import { Configuration } from './configuration';
import customAxios from './customAxios';

const bkPath = window.APP_CONFIG.REST_API_URL;
const config = new Configuration({ basePath: bkPath });

const defaultApi = new DefaultApi(config, bkPath, customAxios);
const imageApi = new ImageApi(config, bkPath, customAxios);
const procImageApi = new ProcImageApi(config, bkPath, customAxios);
const targetImagesApi = new TargetImagesApi(config, bkPath, customAxios);

export * from "./api";
export * from "./configuration";
export { defaultApi, imageApi, procImageApi, targetImagesApi };