/* tslint:disable */
/* eslint-disable */
/**
 * Image Auto Editor API
 * 이미지 자동 편집을 위한 REST API 서비스
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TargetImageResponse } from './target-image-response';
 /**
 * 
 *
 * @export
 * @interface BodyUpdateTargetImageApiTargetImagesImageIdPut
 */
export interface BodyUpdateTargetImageApiTargetImagesImageIdPut {

    /**
     * @type {TargetImageResponse}
     * @memberof BodyUpdateTargetImageApiTargetImagesImageIdPut
     */
    image: TargetImageResponse;

    /**
     * name
     *
     * @type {any}
     * @memberof BodyUpdateTargetImageApiTargetImagesImageIdPut
     */
    name?: any;

    /**
     * tag
     *
     * @type {any}
     * @memberof BodyUpdateTargetImageApiTargetImagesImageIdPut
     */
    tags?: any;

    /**
     * status
     *
     * @type {any}
     * @memberof BodyUpdateTargetImageApiTargetImagesImageIdPut
     */
    isActive?: any;
}
