/* tslint:disable */
/* eslint-disable */
/**
 * Image Auto Editor API
 * 이미지 자동 편집을 위한 REST API 서비스
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TargetImageListResponse
 */
export interface TargetImageListResponse {

    /**
     * @type {any}
     * @memberof TargetImageListResponse
     */
    items: any;

    /**
     * @type {any}
     * @memberof TargetImageListResponse
     */
    page: any;

    /**
     * @type {any}
     * @memberof TargetImageListResponse
     */
    cnt: any;
}
