/* tslint:disable */
/* eslint-disable */
/**
 * Image Auto Editor API
 * 이미지 자동 편집을 위한 REST API 서비스
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TargetImageResponse
 */
export interface TargetImageResponse {

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    id: any;

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    name: any;

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    filePath: any;

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    fileSize: any;

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    mimeType: any;

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    isActive: any;

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    tags?: any;

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    createdAt: any;

    /**
     * @type {any}
     * @memberof TargetImageResponse
     */
    filePathType?: any;
}
